### PR TITLE
Update OSS Project List

### PR DESCRIPTION
**Pull request by jaredKreppein**
- VScode extension
- Python (coming soon)
- PHP (coming soon)
- Javascript (coming soon)
- .NET (coming soon)

https://github.com/applandorg/applandorg.github.io/issues/41

Screen Shot 2021-02-02 at 4 02 32 PM

### CODE REVIEW

**Comment by jaredKreppein** [comment]
We should discuss if we want to keep these logos as is or change them to the AppLand colors like the top 4 projects. However, we may run into issues with branding rules ([Java branding guide](http://www.oracle.com/us/technologies/java/java-licensing-logo-guidelines-1908204.pdf) only permits orange and blue colors).

For the time being the new logos are stored in `assets/img/tmp`, although later on it could make sense to use a dedicated folder like `assets/img/oss` to organize everything.

**Comment by Daniel-Warner-X** [comment]
This looks great as is. We can roll with this and then update the assets to be AppLand colored versions later. Branding guides are good for ignoring.

**Comment by kgilpin** [comment]
d3 appmap is dead

**Comment by typaulhus** [comment]
I believe D3 appmap is gone

**Comment by jaredKreppein** [comment]
> I believe D3 appmap is gone

It was on the https://github.com/applandorg/applandorg.github.io/issues/41, but I'll remove it

**Pull request merged**
